### ISSUE TITLE
Question about Protein Surface 

### ISSUE THREAD

**Issue by smiles724** [stemylonas/DeepSurf#6]
Hi, nice work on the protein-ligand problem, and make this code public.

However, I cannot find the part corresponding to the generation of the protein surface. Can you please show me how to obtain the surface of any protein given its atomic coordinates? 

Thanks

**Comment by stemylonas** [comment]
The surface is generated in 'protein.py, line 22' with the use of DMS software.
 You can download it from [(https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/midas/dms1.html)](https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/midas/dms1.html)
