### ISSUE TITLE
Issues with setting up

### ISSUE THREAD

**Issue by SSchott** [stemylonas/DeepSurf#8]
I found multiple issues until I managed to make this work:
- The import of resnet_3d_utils.py in net/resnet_3d.py does not consider the relative path
- pip installs the latest protobuf, which doesn't work. Had to force 3.6.1.
- As I used conda, didn't manage to get a proper CUDA 9.0 toolkit to make it run. Using tensorflow 1.13.1 with CUDA 10.0 did the trick.
- The "lds/compile" step is unclear, whether it has to be executed from the root folder, or within the lds folder. Due to the file construction, I guess running it within lds is the proper way. The lib folder should be created by the script. The gcc version could be checked there as well.

**Comment by mattrmd** [comment]
@SSchott Do you have a fork with your modified version of DeepSurf? I tried following the README and your above comments, but I'm having a difficult time getting all the old package versions to work together.
